/*********************************************************************************
# COPYRIGHT 2014 OBSERVATIONAL HEALTH DATA SCIENCES AND INFORMATICS
#
#
# LICENSED UNDER THE APACHE LICENSE, VERSION 2.0 (THE "LICENSE")
# YOU MAY NOT USE THIS FILE EXCEPT IN COMPLIANCE WITH THE LICENSE.
# YOU MAY OBTAIN A COPY OF THE LICENSE AT
#
#     HTTP://WWW.APACHE.ORG/LICENSES/LICENSE-2.0
#
# UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING, SOFTWARE
# DISTRIBUTED UNDER THE LICENSE IS DISTRIBUTED ON AN "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.
# SEE THE LICENSE FOR THE SPECIFIC LANGUAGE GOVERNING PERMISSIONS AND
# LIMITATIONS UNDER THE LICENSE.
********************************************************************************/

/************************

 ####### #     # ####### ######      #####  ######  #     #           #######      #####      #####
 #     # ##   ## #     # #     #    #     # #     # ##   ##    #    # #           #     #    #     #  ####  #    #  ####  ##### #####    ##   # #    # #####  ####
 #     # # # # # #     # #     #    #       #     # # # # #    #    # #                 #    #       #    # ##   # #        #   #    #  #  #  # ##   #   #   #
 #     # #  #  # #     # ######     #       #     # #  #  #    #    # ######       #####     #       #    # # #  #  ####    #   #    # #    # # # #  #   #    ####
 #     # #     # #     # #          #       #     # #     #    #    #       # ###       #    #       #    # #  # #      #   #   #####  ###### # #  # #   #        #
 #     # #     # #     # #          #     # #     # #     #     #  #  #     # ### #     #    #     # #    # #   ## #    #   #   #   #  #    # # #   ##   #   #    #
 ####### #     # ####### #           #####  ######  #     #      ##    #####  ###  #####      #####   ####  #    #  ####    #   #    # #    # # #    #   #    ####


POSTGRESQL SCRIPT TO CREATE FOREIGN KEY CONSTRAINTS WITHIN OMOP COMMON DATA MODEL, VERSION 5.3.0

LAST REVISED: 14-JUNE-2018

AUTHOR:  PATRICK RYAN, CLAIR BLACKETER


*************************/


/************************
*************************
*************************
*************************

FOREIGN KEY CONSTRAINTS

*************************
*************************
*************************
************************/


/************************

STANDARDIZED VOCABULARY

************************/
SET search_path to 'cdm';

ALTER TABLE cdm.CONCEPT ADD CONSTRAINT FPK_CONCEPT_DOMAIN FOREIGN KEY (DOMAIN_ID)  REFERENCES DOMAIN (DOMAIN_ID);

ALTER TABLE cdm.CONCEPT ADD CONSTRAINT FPK_CONCEPT_CLASS FOREIGN KEY (CONCEPT_CLASS_ID)  REFERENCES CONCEPT_CLASS (CONCEPT_CLASS_ID);

ALTER TABLE cdm.CONCEPT ADD CONSTRAINT FPK_CONCEPT_VOCABULARY FOREIGN KEY (VOCABULARY_ID)  REFERENCES VOCABULARY (VOCABULARY_ID);

ALTER TABLE cdm.VOCABULARY ADD CONSTRAINT FPK_VOCABULARY_CONCEPT FOREIGN KEY (VOCABULARY_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.DOMAIN ADD CONSTRAINT FPK_DOMAIN_CONCEPT FOREIGN KEY (DOMAIN_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.CONCEPT_CLASS ADD CONSTRAINT FPK_CONCEPT_CLASS_CONCEPT FOREIGN KEY (CONCEPT_CLASS_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.CONCEPT_RELATIONSHIP ADD CONSTRAINT FPK_CONCEPT_RELATIONSHIP_C_1 FOREIGN KEY (CONCEPT_ID_1)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.CONCEPT_RELATIONSHIP ADD CONSTRAINT FPK_CONCEPT_RELATIONSHIP_C_2 FOREIGN KEY (CONCEPT_ID_2)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.CONCEPT_RELATIONSHIP ADD CONSTRAINT FPK_CONCEPT_RELATIONSHIP_ID FOREIGN KEY (RELATIONSHIP_ID)  REFERENCES RELATIONSHIP (RELATIONSHIP_ID);

ALTER TABLE cdm.RELATIONSHIP ADD CONSTRAINT FPK_RELATIONSHIP_CONCEPT FOREIGN KEY (RELATIONSHIP_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.RELATIONSHIP ADD CONSTRAINT FPK_RELATIONSHIP_REVERSE FOREIGN KEY (REVERSE_RELATIONSHIP_ID)  REFERENCES RELATIONSHIP (RELATIONSHIP_ID);

ALTER TABLE cdm.CONCEPT_SYNONYM ADD CONSTRAINT FPK_CONCEPT_SYNONYM_CONCEPT FOREIGN KEY (CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.CONCEPT_SYNONYM ADD CONSTRAINT FPK_CONCEPT_SYNONYM_LANGUAGE FOREIGN KEY (LANGUAGE_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.CONCEPT_ANCESTOR ADD CONSTRAINT FPK_CONCEPT_ANCESTOR_CONCEPT_1 FOREIGN KEY (ANCESTOR_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.CONCEPT_ANCESTOR ADD CONSTRAINT FPK_CONCEPT_ANCESTOR_CONCEPT_2 FOREIGN KEY (DESCENDANT_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.SOURCE_TO_CONCEPT_MAP ADD CONSTRAINT FPK_SOURCE_TO_CONCEPT_MAP_V_1 FOREIGN KEY (SOURCE_VOCABULARY_ID)  REFERENCES VOCABULARY (VOCABULARY_ID);

ALTER TABLE cdm.SOURCE_TO_CONCEPT_MAP ADD CONSTRAINT FPK_SOURCE_CONCEPT_ID FOREIGN KEY (SOURCE_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.SOURCE_TO_CONCEPT_MAP ADD CONSTRAINT FPK_SOURCE_TO_CONCEPT_MAP_V_2 FOREIGN KEY (TARGET_VOCABULARY_ID)  REFERENCES VOCABULARY (VOCABULARY_ID);

ALTER TABLE cdm.SOURCE_TO_CONCEPT_MAP ADD CONSTRAINT FPK_SOURCE_TO_CONCEPT_MAP_C_1 FOREIGN KEY (TARGET_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.DRUG_STRENGTH ADD CONSTRAINT FPK_DRUG_STRENGTH_CONCEPT_1 FOREIGN KEY (DRUG_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.DRUG_STRENGTH ADD CONSTRAINT FPK_DRUG_STRENGTH_CONCEPT_2 FOREIGN KEY (INGREDIENT_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.DRUG_STRENGTH ADD CONSTRAINT FPK_DRUG_STRENGTH_UNIT_1 FOREIGN KEY (AMOUNT_UNIT_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.DRUG_STRENGTH ADD CONSTRAINT FPK_DRUG_STRENGTH_UNIT_2 FOREIGN KEY (NUMERATOR_UNIT_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.DRUG_STRENGTH ADD CONSTRAINT FPK_DRUG_STRENGTH_UNIT_3 FOREIGN KEY (DENOMINATOR_UNIT_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.COHORT_DEFINITION ADD CONSTRAINT FPK_COHORT_DEFINITION_CONCEPT FOREIGN KEY (DEFINITION_TYPE_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.COHORT_DEFINITION ADD CONSTRAINT FPK_COHORT_SUBJECT_CONCEPT FOREIGN KEY (SUBJECT_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.ATTRIBUTE_DEFINITION ADD CONSTRAINT FPK_ATTRIBUTE_TYPE_CONCEPT FOREIGN KEY (ATTRIBUTE_TYPE_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);


/**************************

STANDARDIZED META-DATA

***************************/





/************************

STANDARDIZED CLINICAL DATA

************************/

ALTER TABLE cdm.PERSON ADD CONSTRAINT FPK_PERSON_GENDER_CONCEPT FOREIGN KEY (GENDER_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.PERSON ADD CONSTRAINT FPK_PERSON_RACE_CONCEPT FOREIGN KEY (RACE_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.PERSON ADD CONSTRAINT FPK_PERSON_ETHNICITY_CONCEPT FOREIGN KEY (ETHNICITY_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.PERSON ADD CONSTRAINT FPK_PERSON_GENDER_CONCEPT_S FOREIGN KEY (GENDER_SOURCE_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.PERSON ADD CONSTRAINT FPK_PERSON_RACE_CONCEPT_S FOREIGN KEY (RACE_SOURCE_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.PERSON ADD CONSTRAINT FPK_PERSON_ETHNICITY_CONCEPT_S FOREIGN KEY (ETHNICITY_SOURCE_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.PERSON ADD CONSTRAINT FPK_PERSON_LOCATION FOREIGN KEY (LOCATION_ID)  REFERENCES LOCATION (LOCATION_ID);

ALTER TABLE cdm.PERSON ADD CONSTRAINT FPK_PERSON_PROVIDER FOREIGN KEY (PROVIDER_ID)  REFERENCES PROVIDER (PROVIDER_ID);

ALTER TABLE cdm.PERSON ADD CONSTRAINT FPK_PERSON_CARE_SITE FOREIGN KEY (CARE_SITE_ID)  REFERENCES CARE_SITE (CARE_SITE_ID);


ALTER TABLE cdm.OBSERVATION_PERIOD ADD CONSTRAINT FPK_OBSERVATION_PERIOD_PERSON FOREIGN KEY (PERSON_ID)  REFERENCES PERSON (PERSON_ID);

ALTER TABLE cdm.OBSERVATION_PERIOD ADD CONSTRAINT FPK_OBSERVATION_PERIOD_CONCEPT FOREIGN KEY (PERIOD_TYPE_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);


ALTER TABLE cdm.SPECIMEN ADD CONSTRAINT FPK_SPECIMEN_PERSON FOREIGN KEY (PERSON_ID)  REFERENCES PERSON (PERSON_ID);

ALTER TABLE cdm.SPECIMEN ADD CONSTRAINT FPK_SPECIMEN_CONCEPT FOREIGN KEY (SPECIMEN_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.SPECIMEN ADD CONSTRAINT FPK_SPECIMEN_TYPE_CONCEPT FOREIGN KEY (SPECIMEN_TYPE_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.SPECIMEN ADD CONSTRAINT FPK_SPECIMEN_UNIT_CONCEPT FOREIGN KEY (UNIT_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.SPECIMEN ADD CONSTRAINT FPK_SPECIMEN_SITE_CONCEPT FOREIGN KEY (ANATOMIC_SITE_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.SPECIMEN ADD CONSTRAINT FPK_SPECIMEN_STATUS_CONCEPT FOREIGN KEY (DISEASE_STATUS_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);


ALTER TABLE cdm.DEATH ADD CONSTRAINT FPK_DEATH_PERSON FOREIGN KEY (PERSON_ID)  REFERENCES PERSON (PERSON_ID);

ALTER TABLE cdm.DEATH ADD CONSTRAINT FPK_DEATH_TYPE_CONCEPT FOREIGN KEY (DEATH_TYPE_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.DEATH ADD CONSTRAINT FPK_DEATH_CAUSE_CONCEPT FOREIGN KEY (CAUSE_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.DEATH ADD CONSTRAINT FPK_DEATH_CAUSE_CONCEPT_S FOREIGN KEY (CAUSE_SOURCE_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);


ALTER TABLE cdm.VISIT_OCCURRENCE ADD CONSTRAINT FPK_VISIT_PERSON FOREIGN KEY (PERSON_ID)  REFERENCES PERSON (PERSON_ID);

ALTER TABLE cdm.VISIT_OCCURRENCE ADD CONSTRAINT FPK_VISIT_TYPE_CONCEPT FOREIGN KEY (VISIT_TYPE_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.VISIT_OCCURRENCE ADD CONSTRAINT FPK_VISIT_PROVIDER FOREIGN KEY (PROVIDER_ID)  REFERENCES PROVIDER (PROVIDER_ID);

ALTER TABLE cdm.VISIT_OCCURRENCE ADD CONSTRAINT FPK_VISIT_CARE_SITE FOREIGN KEY (CARE_SITE_ID)  REFERENCES CARE_SITE (CARE_SITE_ID);

ALTER TABLE cdm.VISIT_OCCURRENCE ADD CONSTRAINT FPK_ VISIT_CONCEPT_S FOREIGN KEY (VISIT_SOURCE_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.VISIT_OCCURRENCE ADD CONSTRAINT FPK_VISIT_ADMITTING_S FOREIGN KEY (ADMITTING_SOURCE_CONCEPT_ID) REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.VISIT_OCCURRENCE ADD CONSTRAINT FPK_VISIT_DISCHARGE FOREIGN KEY (DISCHARGE_TO_CONCEPT_ID) REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.VISIT_OCCURRENCE ADD CONSTRAINT FPK_VISIT_PRECEDING FOREIGN KEY (PRECEDING_VISIT_OCCURRENCE_ID) REFERENCES VISIT_OCCURRENCE (VISIT_OCCURRENCE_ID);


ALTER TABLE cdm.VISIT_DETAIL ADD CONSTRAINT FPK_V_DETAIL_PERSON FOREIGN KEY (PERSON_ID)  REFERENCES PERSON (PERSON_ID);

ALTER TABLE cdm.VISIT_DETAIL ADD CONSTRAINT FPK_V_DETAIL_TYPE_CONCEPT FOREIGN KEY (VISIT_DETAIL_TYPE_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.VISIT_DETAIL ADD CONSTRAINT FPK_V_DETAIL_PROVIDER FOREIGN KEY (PROVIDER_ID)  REFERENCES PROVIDER (PROVIDER_ID);

ALTER TABLE cdm.VISIT_DETAIL ADD CONSTRAINT FPK_V_DETAIL_CARE_SITE FOREIGN KEY (CARE_SITE_ID)  REFERENCES CARE_SITE (CARE_SITE_ID);

ALTER TABLE cdm.VISIT_DETAIL ADD CONSTRAINT FPK_V_DETAIL_CONCEPT_S FOREIGN KEY (VISIT_DETAIL_SOURCE_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.VISIT_DETAIL ADD CONSTRAINT FPK_V_DETAIL_ADMITTING_S FOREIGN KEY (ADMITTING_SOURCE_CONCEPT_ID) REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.VISIT_DETAIL ADD CONSTRAINT FPK_V_DETAIL_DISCHARGE FOREIGN KEY (DISCHARGE_TO_CONCEPT_ID) REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.VISIT_DETAIL ADD CONSTRAINT FPK_V_DETAIL_PRECEDING FOREIGN KEY (PRECEDING_VISIT_DETAIL_ID) REFERENCES VISIT_DETAIL (VISIT_DETAIL_ID);

ALTER TABLE cdm.VISIT_DETAIL ADD CONSTRAINT FPK_V_DETAIL_PARENT FOREIGN KEY (VISIT_DETAIL_PARENT_ID) REFERENCES VISIT_DETAIL (VISIT_DETAIL_ID);

ALTER TABLE cdm.VISIT_DETAIL ADD CONSTRAINT FPD_V_DETAIL_VISIT FOREIGN KEY (VISIT_OCCURRENCE_ID) REFERENCES VISIT_OCCURRENCE (VISIT_OCCURRENCE_ID);


ALTER TABLE cdm.PROCEDURE_OCCURRENCE ADD CONSTRAINT FPK_PROCEDURE_PERSON FOREIGN KEY (PERSON_ID)  REFERENCES PERSON (PERSON_ID);

ALTER TABLE cdm.PROCEDURE_OCCURRENCE ADD CONSTRAINT FPK_PROCEDURE_CONCEPT FOREIGN KEY (PROCEDURE_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.PROCEDURE_OCCURRENCE ADD CONSTRAINT FPK_PROCEDURE_TYPE_CONCEPT FOREIGN KEY (PROCEDURE_TYPE_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.PROCEDURE_OCCURRENCE ADD CONSTRAINT FPK_PROCEDURE_MODIFIER FOREIGN KEY (MODIFIER_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.PROCEDURE_OCCURRENCE ADD CONSTRAINT FPK_PROCEDURE_PROVIDER FOREIGN KEY (PROVIDER_ID)  REFERENCES PROVIDER (PROVIDER_ID);

ALTER TABLE cdm.PROCEDURE_OCCURRENCE ADD CONSTRAINT FPK_PROCEDURE_VISIT FOREIGN KEY (VISIT_OCCURRENCE_ID)  REFERENCES VISIT_OCCURRENCE (VISIT_OCCURRENCE_ID);

ALTER TABLE cdm.PROCEDURE_OCCURRENCE ADD CONSTRAINT FPK_PROCEDURE_CONCEPT_S FOREIGN KEY (PROCEDURE_SOURCE_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);


ALTER TABLE cdm.DRUG_EXPOSURE ADD CONSTRAINT FPK_DRUG_PERSON FOREIGN KEY (PERSON_ID)  REFERENCES PERSON (PERSON_ID);

ALTER TABLE cdm.DRUG_EXPOSURE ADD CONSTRAINT FPK_DRUG_CONCEPT FOREIGN KEY (DRUG_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.DRUG_EXPOSURE ADD CONSTRAINT FPK_DRUG_TYPE_CONCEPT FOREIGN KEY (DRUG_TYPE_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.DRUG_EXPOSURE ADD CONSTRAINT FPK_DRUG_ROUTE_CONCEPT FOREIGN KEY (ROUTE_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.DRUG_EXPOSURE ADD CONSTRAINT FPK_DRUG_PROVIDER FOREIGN KEY (PROVIDER_ID)  REFERENCES PROVIDER (PROVIDER_ID);

ALTER TABLE cdm.DRUG_EXPOSURE ADD CONSTRAINT FPK_DRUG_VISIT FOREIGN KEY (VISIT_OCCURRENCE_ID)  REFERENCES VISIT_OCCURRENCE (VISIT_OCCURRENCE_ID);

ALTER TABLE cdm.DRUG_EXPOSURE ADD CONSTRAINT FPK_DRUG_CONCEPT_S FOREIGN KEY (DRUG_SOURCE_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);


ALTER TABLE cdm.DEVICE_EXPOSURE ADD CONSTRAINT FPK_DEVICE_PERSON FOREIGN KEY (PERSON_ID)  REFERENCES PERSON (PERSON_ID);

ALTER TABLE cdm.DEVICE_EXPOSURE ADD CONSTRAINT FPK_DEVICE_CONCEPT FOREIGN KEY (DEVICE_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.DEVICE_EXPOSURE ADD CONSTRAINT FPK_DEVICE_TYPE_CONCEPT FOREIGN KEY (DEVICE_TYPE_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.DEVICE_EXPOSURE ADD CONSTRAINT FPK_DEVICE_PROVIDER FOREIGN KEY (PROVIDER_ID)  REFERENCES PROVIDER (PROVIDER_ID);

ALTER TABLE cdm.DEVICE_EXPOSURE ADD CONSTRAINT FPK_DEVICE_VISIT FOREIGN KEY (VISIT_OCCURRENCE_ID)  REFERENCES VISIT_OCCURRENCE (VISIT_OCCURRENCE_ID);

ALTER TABLE cdm.DEVICE_EXPOSURE ADD CONSTRAINT FPK_DEVICE_CONCEPT_S FOREIGN KEY (DEVICE_SOURCE_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);


ALTER TABLE cdm.CONDITION_OCCURRENCE ADD CONSTRAINT FPK_CONDITION_PERSON FOREIGN KEY (PERSON_ID)  REFERENCES PERSON (PERSON_ID);

ALTER TABLE cdm.CONDITION_OCCURRENCE ADD CONSTRAINT FPK_CONDITION_CONCEPT FOREIGN KEY (CONDITION_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.CONDITION_OCCURRENCE ADD CONSTRAINT FPK_CONDITION_TYPE_CONCEPT FOREIGN KEY (CONDITION_TYPE_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.CONDITION_OCCURRENCE ADD CONSTRAINT FPK_CONDITION_PROVIDER FOREIGN KEY (PROVIDER_ID)  REFERENCES PROVIDER (PROVIDER_ID);

ALTER TABLE cdm.CONDITION_OCCURRENCE ADD CONSTRAINT FPK_CONDITION_VISIT FOREIGN KEY (VISIT_OCCURRENCE_ID)  REFERENCES VISIT_OCCURRENCE (VISIT_OCCURRENCE_ID);

ALTER TABLE cdm.CONDITION_OCCURRENCE ADD CONSTRAINT FPK_CONDITION_CONCEPT_S FOREIGN KEY (CONDITION_SOURCE_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.CONDITION_OCCURRENCE ADD CONSTRAINT FPK_CONDITION_STATUS_CONCEPT FOREIGN KEY (CONDITION_STATUS_CONCEPT_ID) REFERENCES CONCEPT (CONCEPT_ID);


ALTER TABLE cdm.MEASUREMENT ADD CONSTRAINT FPK_MEASUREMENT_PERSON FOREIGN KEY (PERSON_ID)  REFERENCES PERSON (PERSON_ID);

ALTER TABLE cdm.MEASUREMENT ADD CONSTRAINT FPK_MEASUREMENT_CONCEPT FOREIGN KEY (MEASUREMENT_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.MEASUREMENT ADD CONSTRAINT FPK_MEASUREMENT_TYPE_CONCEPT FOREIGN KEY (MEASUREMENT_TYPE_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.MEASUREMENT ADD CONSTRAINT FPK_MEASUREMENT_OPERATOR FOREIGN KEY (OPERATOR_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.MEASUREMENT ADD CONSTRAINT FPK_MEASUREMENT_VALUE FOREIGN KEY (VALUE_AS_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.MEASUREMENT ADD CONSTRAINT FPK_MEASUREMENT_UNIT FOREIGN KEY (UNIT_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.MEASUREMENT ADD CONSTRAINT FPK_MEASUREMENT_PROVIDER FOREIGN KEY (PROVIDER_ID)  REFERENCES PROVIDER (PROVIDER_ID);

ALTER TABLE cdm.MEASUREMENT ADD CONSTRAINT FPK_MEASUREMENT_VISIT FOREIGN KEY (VISIT_OCCURRENCE_ID)  REFERENCES VISIT_OCCURRENCE (VISIT_OCCURRENCE_ID);

ALTER TABLE cdm.MEASUREMENT ADD CONSTRAINT FPK_MEASUREMENT_CONCEPT_S FOREIGN KEY (MEASUREMENT_SOURCE_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);


ALTER TABLE cdm.NOTE ADD CONSTRAINT FPK_NOTE_PERSON FOREIGN KEY (PERSON_ID)  REFERENCES PERSON (PERSON_ID);

ALTER TABLE cdm.NOTE ADD CONSTRAINT FPK_NOTE_TYPE_CONCEPT FOREIGN KEY (NOTE_TYPE_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.NOTE ADD CONSTRAINT FPK_NOTE_CLASS_CONCEPT FOREIGN KEY (NOTE_CLASS_CONCEPT_ID) REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.NOTE ADD CONSTRAINT FPK_NOTE_ENCODING_CONCEPT FOREIGN KEY (ENCODING_CONCEPT_ID) REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.NOTE ADD CONSTRAINT FPK_LANGUAGE_CONCEPT FOREIGN KEY (LANGUAGE_CONCEPT_ID) REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.NOTE ADD CONSTRAINT FPK_NOTE_PROVIDER FOREIGN KEY (PROVIDER_ID)  REFERENCES PROVIDER (PROVIDER_ID);

ALTER TABLE cdm.NOTE ADD CONSTRAINT FPK_NOTE_VISIT FOREIGN KEY (VISIT_OCCURRENCE_ID)  REFERENCES VISIT_OCCURRENCE (VISIT_OCCURRENCE_ID);


ALTER TABLE cdm.NOTE_NLP ADD CONSTRAINT FPK_NOTE_NLP_NOTE FOREIGN KEY (NOTE_ID) REFERENCES NOTE (NOTE_ID);

ALTER TABLE cdm.NOTE_NLP ADD CONSTRAINT FPK_NOTE_NLP_SECTION_CONCEPT FOREIGN KEY (SECTION_CONCEPT_ID) REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.NOTE_NLP ADD CONSTRAINT FPK_NOTE_NLP_CONCEPT FOREIGN KEY (NOTE_NLP_CONCEPT_ID) REFERENCES CONCEPT (CONCEPT_ID);



ALTER TABLE cdm.OBSERVATION ADD CONSTRAINT FPK_OBSERVATION_PERSON FOREIGN KEY (PERSON_ID)  REFERENCES PERSON (PERSON_ID);

ALTER TABLE cdm.OBSERVATION ADD CONSTRAINT FPK_OBSERVATION_CONCEPT FOREIGN KEY (OBSERVATION_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.OBSERVATION ADD CONSTRAINT FPK_OBSERVATION_TYPE_CONCEPT FOREIGN KEY (OBSERVATION_TYPE_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.OBSERVATION ADD CONSTRAINT FPK_OBSERVATION_VALUE FOREIGN KEY (VALUE_AS_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.OBSERVATION ADD CONSTRAINT FPK_OBSERVATION_QUALIFIER FOREIGN KEY (QUALIFIER_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.OBSERVATION ADD CONSTRAINT FPK_OBSERVATION_UNIT FOREIGN KEY (UNIT_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.OBSERVATION ADD CONSTRAINT FPK_OBSERVATION_PROVIDER FOREIGN KEY (PROVIDER_ID)  REFERENCES PROVIDER (PROVIDER_ID);

ALTER TABLE cdm.OBSERVATION ADD CONSTRAINT FPK_OBSERVATION_VISIT FOREIGN KEY (VISIT_OCCURRENCE_ID)  REFERENCES VISIT_OCCURRENCE (VISIT_OCCURRENCE_ID);

ALTER TABLE cdm.OBSERVATION ADD CONSTRAINT FPK_OBSERVATION_CONCEPT_S FOREIGN KEY (OBSERVATION_SOURCE_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);


ALTER TABLE cdm.FACT_RELATIONSHIP ADD CONSTRAINT FPK_FACT_DOMAIN_1 FOREIGN KEY (DOMAIN_CONCEPT_ID_1)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.FACT_RELATIONSHIP ADD CONSTRAINT FPK_FACT_DOMAIN_2 FOREIGN KEY (DOMAIN_CONCEPT_ID_2)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.FACT_RELATIONSHIP ADD CONSTRAINT FPK_FACT_RELATIONSHIP FOREIGN KEY (RELATIONSHIP_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);



/************************

STANDARDIZED HEALTH SYSTEM DATA

************************/

ALTER TABLE cdm.CARE_SITE ADD CONSTRAINT FPK_CARE_SITE_LOCATION FOREIGN KEY (LOCATION_ID)  REFERENCES LOCATION (LOCATION_ID);

ALTER TABLE cdm.CARE_SITE ADD CONSTRAINT FPK_CARE_SITE_PLACE FOREIGN KEY (PLACE_OF_SERVICE_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);


ALTER TABLE cdm.PROVIDER ADD CONSTRAINT FPK_PROVIDER_SPECIALTY FOREIGN KEY (SPECIALTY_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.PROVIDER ADD CONSTRAINT FPK_PROVIDER_CARE_SITE FOREIGN KEY (CARE_SITE_ID)  REFERENCES CARE_SITE (CARE_SITE_ID);

ALTER TABLE cdm.PROVIDER ADD CONSTRAINT FPK_PROVIDER_GENDER FOREIGN KEY (GENDER_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.PROVIDER ADD CONSTRAINT FPK_PROVIDER_SPECIALTY_S FOREIGN KEY (SPECIALTY_SOURCE_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.PROVIDER ADD CONSTRAINT FPK_PROVIDER_GENDER_S FOREIGN KEY (GENDER_SOURCE_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);




/************************

STANDARDIZED HEALTH ECONOMICS

************************/

ALTER TABLE cdm.PAYER_PLAN_PERIOD ADD CONSTRAINT FPK_PAYER_PLAN_PERIOD FOREIGN KEY (PERSON_ID)  REFERENCES PERSON (PERSON_ID);

ALTER TABLE cdm.COST ADD CONSTRAINT FPK_VISIT_COST_CURRENCY FOREIGN KEY (CURRENCY_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.COST ADD CONSTRAINT FPK_VISIT_COST_PERIOD FOREIGN KEY (PAYER_PLAN_PERIOD_ID)  REFERENCES PAYER_PLAN_PERIOD (PAYER_PLAN_PERIOD_ID);

ALTER TABLE cdm.COST ADD CONSTRAINT FPK_DRG_CONCEPT FOREIGN KEY (DRG_CONCEPT_ID) REFERENCES CONCEPT (CONCEPT_ID);

/************************

STANDARDIZED DERIVED ELEMENTS

************************/


--ALTER TABLE cdm.COHORT ADD CONSTRAINT FPK_COHORT_DEFINITION FOREIGN KEY (COHORT_DEFINITION_ID)  REFERENCES COHORT_DEFINITION (COHORT_DEFINITION_ID);


ALTER TABLE cdm.COHORT_ATTRIBUTE ADD CONSTRAINT FPK_CA_COHORT_DEFINITION FOREIGN KEY (COHORT_DEFINITION_ID)  REFERENCES COHORT_DEFINITION (COHORT_DEFINITION_ID);

ALTER TABLE cdm.COHORT_ATTRIBUTE ADD CONSTRAINT FPK_CA_ATTRIBUTE_DEFINITION FOREIGN KEY (ATTRIBUTE_DEFINITION_ID)  REFERENCES ATTRIBUTE_DEFINITION (ATTRIBUTE_DEFINITION_ID);

ALTER TABLE cdm.COHORT_ATTRIBUTE ADD CONSTRAINT FPK_CA_VALUE FOREIGN KEY (VALUE_AS_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);


ALTER TABLE cdm.DRUG_ERA ADD CONSTRAINT FPK_DRUG_ERA_PERSON FOREIGN KEY (PERSON_ID)  REFERENCES PERSON (PERSON_ID);

ALTER TABLE cdm.DRUG_ERA ADD CONSTRAINT FPK_DRUG_ERA_CONCEPT FOREIGN KEY (DRUG_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);


ALTER TABLE cdm.DOSE_ERA ADD CONSTRAINT FPK_DOSE_ERA_PERSON FOREIGN KEY (PERSON_ID)  REFERENCES PERSON (PERSON_ID);

ALTER TABLE cdm.DOSE_ERA ADD CONSTRAINT FPK_DOSE_ERA_CONCEPT FOREIGN KEY (DRUG_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);

ALTER TABLE cdm.DOSE_ERA ADD CONSTRAINT FPK_DOSE_ERA_UNIT_CONCEPT FOREIGN KEY (UNIT_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);


ALTER TABLE cdm.CONDITION_ERA ADD CONSTRAINT FPK_CONDITION_ERA_PERSON FOREIGN KEY (PERSON_ID)  REFERENCES PERSON (PERSON_ID);

ALTER TABLE cdm.CONDITION_ERA ADD CONSTRAINT FPK_CONDITION_ERA_CONCEPT FOREIGN KEY (CONDITION_CONCEPT_ID)  REFERENCES CONCEPT (CONCEPT_ID);


/************************
*************************
*************************
*************************

UNIQUE CONSTRAINTS

*************************
*************************
*************************
************************/

ALTER TABLE cdm.CONCEPT_SYNONYM ADD CONSTRAINT UQ_CONCEPT_SYNONYM UNIQUE (CONCEPT_ID, CONCEPT_SYNONYM_NAME, LANGUAGE_CONCEPT_ID);
