version: '3.8'

services:

  db:
    image: postgres:13.3-alpine
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  rutils:
    volumes:
      - ./scripts:/usr/scripts
  
volumes:
  postgres_data:
